Repository Sergio0694/ComputeSharp, pull requests merged in 2021-11, with the labels that each got.

#148 Hlsl.Distance output to scalar float
  src/ComputeSharp/Core/Intrinsics/Hlsl.g.cs
  src/ComputeSharp/Core/Intrinsics/Hlsl.ttinclude
Labels: bug fix :white_check_mark:

#146 Win32 sample improvements
  samples/ComputeSharp.SwapChain/Backend/Win32ApplicationRunner.cs
  samples/ComputeSharp.SwapChain/Program.cs
Labels: samples :books:

#147 Add FourColorGradient Sample
  README.md
  samples/ComputeSharp.SwapChain/Program.cs
  samples/ComputeSharp.SwapChain/Shaders/FourColorGradient.cs
  tests/ComputeSharp.Tests/Assets/FourColorGradient.png
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
  tests/ComputeSharp.Tests/Shaders/Compute/FourColorGradient.cs
  tests/ComputeSharp.Tests/ShadersTests.cs
Labels: samples :books:

#161 Expand resource copying APIs
  src/ComputeSharp/Core/Helpers/AlignmentHelper.cs
  src/ComputeSharp/Graphics/Extensions/BufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Interop/ID3D12GraphicsCommandListExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadBackBufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadBackTexture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadBackTexture3DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/StructuredBufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Texture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Texture3DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/UploadBufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/UploadTexture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/UploadTexture3DExtensions.cs
  src/ComputeSharp/Graphics/Helpers/MemoryHelper.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Buffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/StructuredBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/ConstantBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Debug/BufferDebugView{T}.cs
  src/ComputeSharp/Graphics/Resources/Debug/Texture2DDebugView{T}.cs
  src/ComputeSharp/Graphics/Resources/Debug/Texture3DDebugView{T}.cs
  src/ComputeSharp/Graphics/Resources/Debug/TransferBufferDebugView{T}.cs
  tests/ComputeSharp.Tests.Internals/ComputeSharp.Tests.Internals.csproj
  tests/ComputeSharp.Tests.Internals/DebugViewTests.cs
  tests/ComputeSharp.Tests/Attributes/AdditionalDataAttribute.cs
  tests/ComputeSharp.Tests/Attributes/AdditionalResourceAttribute.cs
  tests/ComputeSharp.Tests/Attributes/CombinatorialTestMethodAttribute.cs
  tests/ComputeSharp.Tests/Attributes/DataAttribute.cs
  tests/ComputeSharp.Tests/Attributes/DeviceAttribute.cs
  tests/ComputeSharp.Tests/Attributes/ResourceAttribute.cs
  tests/ComputeSharp.Tests/BufferTests.cs
  tests/ComputeSharp.Tests/Texture2DTests.cs
  tests/ComputeSharp.Tests/Texture3DTests.cs
  tests/ComputeSharp.Tests/TransferBufferTests.cs
Labels: enhancement :sparkles:

#163 Switch to COM support in D3D12MA
  samples/ComputeSharp.SwapChain/Backend/SwapChainApplication{T}.cs
  samples/ComputeSharp.SwapChain/Backend/Win32Application.cs
  samples/ComputeSharp.SwapChain/Backend/Win32ApplicationRunner.cs
  src/ComputeSharp/ComputeSharp.csproj
  src/ComputeSharp/Graphics/Commands/CommandList.cs
  src/ComputeSharp/Graphics/Commands/Interop/ID3D12CommandListPool.cs
  src/ComputeSharp/Graphics/Commands/Interop/ID3D12DescriptorHandleAllocator.cs
  src/ComputeSharp/Graphics/Commands/PipelineData.cs
  src/ComputeSharp/Graphics/Extensions/Interop/AllocatorExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Interop/ComPtrExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Interop/HResultExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Interop/ID3D12DeviceExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Interop/ID3D12GraphicsCommandListExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Interop/ID3D12ResourceExtensions.cs
  src/ComputeSharp/Graphics/GraphicsDevice.cs
  src/ComputeSharp/Graphics/GraphicsDeviceInfo.cs
  src/ComputeSharp/Graphics/Helpers/D3D12FeatureHelper.cs
  src/ComputeSharp/Graphics/Helpers/DXGIFormatHelper.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.Enumerator.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.Factory.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.ID3D12InfoQueue.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.IDXGIFactory6.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.cs
  src/ComputeSharp/Graphics/Helpers/WICFormatHelper.cs
  src/ComputeSharp/Graphics/Helpers/WICHelper.cs
  src/ComputeSharp/Graphics/Helpers/__Internals/GraphicsResourceHelper.cs
  src/ComputeSharp/Graphics/Interop/ReferenceCountPtr{T}.cs
  src/ComputeSharp/Graphics/Interop/UniquePtr{T}.cs
  src/ComputeSharp/Graphics/Luid.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Buffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/StructuredBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/ConstantBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Enums/ResourceType.cs
  src/ComputeSharp/Graphics/Resources/Interop/ID3D12ResourceMap.cs
  src/ComputeSharp/Graphics/Resources/Interop/__Internals/ResourceDescriptor.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture2D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture3D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture2D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture3D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture3D{T}.cs
  src/ComputeSharp/Shaders/Dispatching/ComputeShaderDispatchDataLoader.cs
  src/ComputeSharp/Shaders/Dispatching/PixelShaderDispatchDataLoader.cs
  src/ComputeSharp/Shaders/Dispatching/ShaderDispatchMetadataLoader.cs
  src/ComputeSharp/Shaders/Extensions/ID3D12DeviceExtensions.cs
  src/ComputeSharp/Shaders/Interop/ReflectionServices.cs
  src/ComputeSharp/Shaders/ShaderRunner{T}.cs
  src/ComputeSharp/Shaders/Translation/Models/CachedShader.cs
  src/ComputeSharp/Shaders/Translation/ShaderCompiler.LibraryLoading.cs
  src/ComputeSharp/Shaders/Translation/ShaderCompiler.cs
  tests/ComputeSharp.Tests.Internals/ShaderCompilerTests.cs
  tests/ComputeSharp.Tests/InteropServicesTests.cs
Labels: enhancement :sparkles:, optimization 🚀, refactoring 🧹

#167 WinUI 3 shader panel
  .github/workflows/dotnet.yml
  .gitignore
  ComputeSharp.NET.slnf
  ComputeSharp.sln
  Directory.Build.props
  samples/ComputeSharp.SwapChain.WinUI/App.xaml
  samples/ComputeSharp.SwapChain.WinUI/App.xaml.cs
  samples/ComputeSharp.SwapChain.WinUI/Assets/LockScreenLogo.scale-200.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/Misc/noise_low.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/SplashScreen.scale-200.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/Square150x150Logo.scale-200.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/Square44x44Logo.scale-200.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/StoreLogo.png
  samples/ComputeSharp.SwapChain.WinUI/Assets/Wide310x150Logo.scale-200.png
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  samples/ComputeSharp.SwapChain.WinUI/Converters/RenderingPauseConverter.cs
  samples/ComputeSharp.SwapChain.WinUI/Converters/ResolutionScaleConverter.cs
  samples/ComputeSharp.SwapChain.WinUI/Models/ComputeShader.cs
  samples/ComputeSharp.SwapChain.WinUI/Package.appxmanifest
  samples/ComputeSharp.SwapChain.WinUI/Properties/PublishProfiles/win10-x64.pubxml
  samples/ComputeSharp.SwapChain.WinUI/Properties/launchSettings.json
  samples/ComputeSharp.SwapChain.WinUI/Shaders/Runners/ContouredLayersRunner.cs
  samples/ComputeSharp.SwapChain.WinUI/ViewModels/MainViewModel.cs
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml.cs
  samples/ComputeSharp.SwapChain.WinUI/app.manifest
  samples/ComputeSharp.SwapChain/ComputeSharp.SwapChain.csproj
  src/ComputeSharp.Package/ComputeSharp.Package.msbuildproj
  src/ComputeSharp.WinUI/ComputeSharp.WinUI.csproj
  src/ComputeSharp.WinUI/Controls/ComputeShaderPanel.Properties.cs
  src/ComputeSharp.WinUI/Controls/ComputeShaderPanel.Rendering.cs
  src/ComputeSharp.WinUI/Controls/ComputeShaderPanel.cs
  src/ComputeSharp.WinUI/Directory.Build.props
  src/ComputeSharp.WinUI/Helpers/DynamicResolutionManager.cs
  src/ComputeSharp.WinUI/IShaderRunner.cs
  src/ComputeSharp.WinUI/ShaderRunner{T}.cs
  src/ComputeSharp/ComputeSharp.csproj
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.IDXGIFactory6.cs
  src/ComputeSharp/Properties/AssemblyInfo.cs
  src/Directory.Build.props
Labels: feature 🎉

#169 Switch Marshal.AllocHGlobal to NativeMemory.Alloc
  src/ComputeSharp.NetStandard/ComputeSharp.NetStandard.projitems
  src/ComputeSharp.NetStandard/System/Runtime/InteropServices/NativeMemory.cs
  src/ComputeSharp.NetStandard/System/Runtime/Versioning/SupportedOSVersionAttribute.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.ID3D12InfoQueue.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.IDXGIFactory6.cs
Labels: optimization 🚀
