Repository Sergio0694/ComputeSharp, pull requests merged in 2022-05, with the labels that each got.

#256 Fix void intrinsics mapping
  src/ComputeSharp.Core/Intrinsics/Hlsl.Void.g.cs
  src/ComputeSharp.Core/Intrinsics/Hlsl.Void.tt
  src/ComputeSharp.Core/Intrinsics/Hlsl.Void.ttinclude
  src/ComputeSharp.Core/Intrinsics/Hlsl.cs
  src/ComputeSharp.Core/Intrinsics/Hlsl.tt
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  tests/ComputeSharp.D2D1.Tests/Assets/Landscape_CheckerboardClip.png
  tests/ComputeSharp.D2D1.Tests/Assets/Landscape_Pixelate.png
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.D2D1.Tests/Effects/CheckerboardClipEffect.cs
  tests/ComputeSharp.D2D1.Tests/Effects/InvertEffect.cs
  tests/ComputeSharp.D2D1.Tests/EndToEndTests.cs
Labels: bug fix :white_check_mark:

#258 Add MS Docs URLs to all HLSL intrinsics
  src/ComputeSharp.Core/Intrinsics/Hlsl.Void.g.cs
  src/ComputeSharp.Core/Intrinsics/Hlsl.Void.tt
  src/ComputeSharp.Core/Intrinsics/Hlsl.Void.ttinclude
  src/ComputeSharp.Core/Intrinsics/Hlsl.cs
  src/ComputeSharp.Core/Intrinsics/Hlsl.g.cs
  src/ComputeSharp.Core/Intrinsics/Hlsl.tt
  src/ComputeSharp.Core/Intrinsics/Hlsl.ttinclude
Labels: enhancement :sparkles:

#263 Fix discovered constants in shader static fields
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.cs
  src/ComputeSharp.SourceGenerators/IShaderGenerator.CreateBuildHlslSourceMethod.cs
  tests/ComputeSharp.Tests/ShaderRewriterTests.cs
Labels: bug fix :white_check_mark:

#264 Add D2D1InteropServices.GetInputType API
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputCountMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputTypeMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputTypeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.D2D1.SourceGenerators/Models/InputTypesInfo.cs
  src/ComputeSharp.D2D1/Helpers/ThrowHelper.cs
  src/ComputeSharp.D2D1/Interfaces/__Internals/ID2D1Shader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1InteropServices.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShaderInputType.cs
  src/ComputeSharp.SourceGeneration/Extensions/IncrementalValuesProviderExtensions.cs
  tests/ComputeSharp.D2D1.Tests/D2D1InteropServicesTests.cs
Labels: feature 🎉

#265 Update default draw transform mapper logic
  src/ComputeSharp.D2D1/Extensions/RECTExtensions.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShaderEffect.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.For{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.ID2D1DrawTransformMethods.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.cs
  src/TerraFX.Interop.Windows.D2D1/Windows/shared/winerror/E.cs
Labels: enhancement :sparkles:

#266 Add [D2DOutputBuffer] attribute and infrastructure
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputCountMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputTypeMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputTypeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetOutputBufferMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetOutputBufferMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateInitializeFromDispatchDataMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadDispatchDataMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.D2D1.SourceGenerators/Models/OutputBufferInfo.cs
  src/ComputeSharp.D2D1/Attributes/D2DEmbeddedBytecodeAttribute.cs
  src/ComputeSharp.D2D1/Attributes/D2DInputComplexAttribute.cs
  src/ComputeSharp.D2D1/Attributes/D2DInputCountAttribute.cs
  src/ComputeSharp.D2D1/Attributes/D2DInputSimpleAttribute.cs
  src/ComputeSharp.D2D1/Attributes/D2DOutputBuffer.cs
  src/ComputeSharp.D2D1/Attributes/D2DRequiresScenePositionAttribute.cs
  src/ComputeSharp.D2D1/Attributes/Enums/D2D1BufferPrecision.cs
  src/ComputeSharp.D2D1/Attributes/Enums/D2D1ChannelDepth.cs
  src/ComputeSharp.D2D1/Attributes/Enums/D2D1ShaderProfile.cs
  src/ComputeSharp.D2D1/Interfaces/__Internals/ID2D1Shader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.For{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.ID2D1DrawTransformMethods.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.cs
  src/ComputeSharp.SourceGeneration/Extensions/ISymbolExtensions.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1_1/D2D1_BUFFER_PRECISION.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1_1/D2D1_CHANNEL_DEPTH.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1effectauthor/ID2D1DrawInfo.cs
  src/TerraFX.Interop.Windows.D2D1/TerraFX.Interop.Windows.D2D1.projitems
  tests/ComputeSharp.D2D1.Tests/D2D1InteropServicesTests.cs
Labels: feature 🎉

#267 Add support for D2D1 input descriptions
  src/ComputeSharp.D2D1.SourceGenerators/AnalyzerReleases.Shipped.md
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/Diagnostics/DiagnosticDescriptors.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputTypeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadInputDescriptionsMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadInputDescriptionsMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.D2D1.SourceGenerators/Models/InputDescription.cs
  src/ComputeSharp.D2D1.SourceGenerators/Models/InputDescriptionsInfo.cs
  src/ComputeSharp.D2D1/Attributes/D2DInputDescriptionAttribute.cs
  src/ComputeSharp.D2D1/Attributes/Enums/D2D1Filter.cs
  src/ComputeSharp.D2D1/Interfaces/__Internals/ID2D1InputDescriptionsLoader.cs
  src/ComputeSharp.D2D1/Interfaces/__Internals/ID2D1Shader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1InputDescription.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShaderEffect.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1ReflectionServices.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.For{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.ID2D1DrawTransformMethods.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1ByteArrayDispatchDataLoader.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1ByteArrayInputDescriptionsLoader.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1DrawInfoDispatchDataLoader.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1EffectDispatchDataLoader.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1ShaderBytecodeLoader.cs
  src/ComputeSharp.SourceGeneration/ComputeSharp.SourceGeneration.projitems
  src/ComputeSharp.SourceGeneration/Extensions/AttributeDataExtensions.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1effectauthor/D2D1_FILTER.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1effectauthor/D2D1_INPUT_DESCRIPTION.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1effectauthor/ID2D1DrawInfo.cs
  src/TerraFX.Interop.Windows.D2D1/TerraFX.Interop.Windows.D2D1.projitems
  tests/ComputeSharp.D2D1.Tests/D2D1InteropServicesTests.cs
Labels: feature 🎉

#269 Add D2D1PixelOption support
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetPixelOptionsMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetPixelOptionsMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.D2D1/Attributes/D2DPixelOptions.cs
  src/ComputeSharp.D2D1/Attributes/Enums/D2D1PixelOptions.cs
  src/ComputeSharp.D2D1/Interfaces/__Internals/ID2D1Shader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.For{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.ID2D1DrawTransformMethods.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.cs
Labels: feature 🎉

#273 Add NuGet build CI logic
  .github/workflows/dotnet.yml
  Directory.Build.props
  Directory.Build.targets
Labels: maintenance ⚙️

#280 Add public D2D1 shader compiler APIs
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1ShaderCompiler.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1ShaderCompilerOptions.cs
  src/ComputeSharp.D2D1/Shaders/Translation/D3DCompiler.ID3DInclude.cs
  src/ComputeSharp.D2D1/Shaders/Translation/D3DCompiler.cs
  src/ComputeSharp.D2D1/Shaders/Translation/__Internals/D2D1ShaderCompiler.cs
  tests/ComputeSharp.D2D1.Tests/D2D1ShaderCompilerTests.cs
Labels: feature 🎉

#281 Add [D2D1CompileOptions] attribute to control bytecode generation
  src/ComputeSharp.D2D1.SourceGenerators/AnalyzerReleases.Shipped.md
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/Diagnostics/DiagnosticDescriptors.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateGetInputTypeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadDispatchDataMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.D2D1.SourceGenerators/Models/EmbeddedBytecodeInfo.cs
  src/ComputeSharp.D2D1.SourceGenerators/Models/HlslShaderSourceInfo.cs
  src/ComputeSharp.D2D1/Attributes/D2DCompileOptionsAttribute.cs
  src/ComputeSharp.D2D1/Attributes/D2DEmbeddedBytecodeAttribute.cs
  src/ComputeSharp.D2D1/Attributes/Enums/D2D1CompileOptions.cs
  src/ComputeSharp.D2D1/Interfaces/__Internals/ID2D1Shader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShader.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1ReflectionServices.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1ShaderCompiler.cs
  src/ComputeSharp.D2D1/Shaders/Translation/D3DCompiler.cs
  src/ComputeSharp.D2D1/Shaders/Translation/__Internals/D2D1ShaderCompiler.cs
  tests/ComputeSharp.D2D1.Tests/D2D1ShaderCompilerTests.cs
Labels: feature 🎉

#283 Add unit tests for embedded bytecode validation
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShader.cs
  tests/ComputeSharp.D2D1.Tests/D2D1PixelShaderTests.cs
  tests/ComputeSharp.D2D1.Tests/D2D1ShaderCompilerTests.cs
Labels: enhancement :sparkles:, maintenance ⚙️

#291 Add [D2DEmbeddedBytecode] and [D2DCompileOptions] assembly-level support
  .github/workflows/dotnet.yml
  ComputeSharp.sln
  src/ComputeSharp.D2D1.SourceGenerators/Diagnostics/DiagnosticDescriptors.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.D2D1/Attributes/D2DCompileOptionsAttribute.cs
  src/ComputeSharp.D2D1/Attributes/D2DEmbeddedBytecodeAttribute.cs
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes.csproj
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/D2D1PixelShaderTests.cs
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/Properties/AssemblyInfo.cs
Labels: feature 🎉

#295 Improve WinUI 3 sample app
  samples/ComputeSharp.SwapChain.WinUI/App.xaml.cs
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  samples/ComputeSharp.SwapChain.WinUI/Properties/PublishProfiles/win10-arm64.pubxml
  samples/ComputeSharp.SwapChain.WinUI/Properties/PublishProfiles/win10-x64.pubxml
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml.cs
Labels: enhancement :sparkles:, bug fix :white_check_mark:

#296 Use AttributeData for [D2DCompileOptions] assembly diagnostics
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
Labels: maintenance ⚙️

#297 Use `GetText` instead of `ToFullString`
  src/ComputeSharp.Core.SourceGenerators/AutoConstructorGenerator.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateLoadBytecodeMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.SourceGenerators/IShaderGenerator.CreateLoadBytecodeMethod.Syntax.cs
  src/ComputeSharp.SourceGenerators/IShaderGenerator.cs
  src/ComputeSharp.SourceGenerators/ShaderMethodSourceGenerator.cs
Labels: optimization 🚀

#299 Add missing ID2D1DrawInfo::AddRef calls
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.ID2D1DrawTransformMethods.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.cs
  src/TerraFX.Interop.Windows.D2D1/DirectX/um/d2d1effectauthor/ID2D1DrawInfo.cs
Labels: bug fix :white_check_mark:

#292 Use raw multiline string literals when possible
  src/ComputeSharp.Core.SourceGenerators/ComputeSharp.Core.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.Syntax.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.CreateBuildHlslSourceMethod.cs
  src/ComputeSharp.D2D1.SourceGenerators/ID2D1ShaderGenerator.cs
  src/ComputeSharp.SourceGenerators/ComputeSharp.SourceGenerators.csproj
  src/ComputeSharp.SourceGenerators/IShaderGenerator.CreateBuildHlslSourceMethod.Syntax.cs
  src/ComputeSharp.SourceGenerators/IShaderGenerator.cs
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes.csproj
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.Tests.DisableDynamicCompilation/ComputeSharp.Tests.DisableDynamicCompilation.csproj
  tests/ComputeSharp.Tests.Internals/ComputeSharp.Tests.Internals.csproj
  tests/ComputeSharp.Tests.NativeLibrariesResolver/ComputeSharp.Tests.NativeLibrariesResolver.csproj
  tests/ComputeSharp.Tests.SourceGenerators/ComputeSharp.Tests.SourceGenerators.csproj
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
Labels: enhancement :sparkles:, breaking change :bomb:

#301 Fix double literals rewriting
  src/ComputeSharp.D2D1.SourceGenerators/SyntaxRewriters/HlslSourceRewriter.cs
  src/ComputeSharp.SourceGenerators/SyntaxRewriters/HlslSourceRewriter.cs
  tests/ComputeSharp.Tests/ShaderRewriterTests.cs
Labels: bug fix :white_check_mark:
