Repository Sergio0694/ComputeSharp, pull requests merged in 2022-11, with the labels that each got.

#424 Update TerraFX.Interop.D3D12MemoryAllocator reference
  src/ComputeSharp/ComputeSharp.csproj
Labels: bug fix :white_check_mark:, optimization 🚀

#423 Add support for reflection-free mode
  samples/ComputeSharp.SwapChain/Backend/Win32ApplicationRunner.cs
  samples/ComputeSharp.SwapChain/Program.cs
  src/ComputeSharp/ComputeSharp.csproj
Labels: bug fix :white_check_mark:, optimization 🚀, samples :books:

#422 Optimize and simplify CI pipeline
  .github/workflows/dotnet.yml
  samples/ComputeSharp.Sample.FSharp.Shaders/ComputeSharp.Sample.FSharp.Shaders.csproj
  samples/ComputeSharp.Sample.FSharp/ComputeSharp.Sample.FSharp.fsproj
Labels: maintenance ⚙️

#426 Simplify CI pipeline
  .github/workflows/dotnet.yml
Labels: maintenance ⚙️

#389 Add ref count check to DeviceLost_RaiseEvent test
  tests/ComputeSharp.Tests.DeviceLost/DeviceLostTests.cs
Labels: maintenance ⚙️

#427 Update .gitattributes to set line endings
  .editorconfig
  .gitattributes
  src/TerraFX.Interop.Windows.D2D1/.editorconfig
  src/TerraFX.Interop.Windows.Dynamic/.editorconfig
  src/TerraFX.Interop.Windows/.editorconfig
Labels: maintenance ⚙️

#433 Add TerracedHills sample
  samples/ComputeSharp.SwapChain.Core.Shared/ViewModels/MainViewModel.cs
  samples/ComputeSharp.SwapChain.Shaders.Shared/ComputeSharp.SwapChain.Shaders.Shared.projitems
  samples/ComputeSharp.SwapChain.Shaders.Shared/TerracedHills.cs
  samples/ComputeSharp.SwapChain/Program.cs
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.D2D1.Tests/Shaders/TerracedHills.cs
  tests/ComputeSharp.D2D1.Tests/ShadersTests.cs
  tests/ComputeSharp.Tests/Assets/TerracedHills.png
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
  tests/ComputeSharp.Tests/Shaders/Compute/TerracedHills.cs
  tests/ComputeSharp.Tests/ShadersTests.cs
Labels: samples :books:

#434 Add shader compiler tests for scoped parameters
  tests/ComputeSharp.Tests/ShaderCompilerTests.cs
Labels: unit tests :test_tube:

#438 Add workaround for dotnet test missing MSBuild properties
  .github/workflows/dotnet.yml
  src/ComputeSharp.Dynamic/ComputeSharp.Dynamic.csproj
Labels: maintenance ⚙️, unit tests :test_tube:

#425 Update to .NET 7 SDK
  Directory.Build.props
  samples/ComputeSharp.Sample.FSharp/ComputeSharp.Sample.FSharp.fsproj
  samples/ComputeSharp.SwapChain.Uwp/ComputeSharp.SwapChain.Uwp.csproj
  src/ComputeSharp.Core.SourceGenerators/ComputeSharp.Core.SourceGenerators.csproj
  src/ComputeSharp.D2D1.SourceGenerators/ComputeSharp.D2D1.SourceGenerators.csproj
  src/ComputeSharp.SourceGenerators/ComputeSharp.SourceGenerators.csproj
  src/ComputeSharp/ComputeSharp.csproj
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes.csproj
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.Tests.DeviceLost/ComputeSharp.Tests.DeviceLost.csproj
  tests/ComputeSharp.Tests.DisableDynamicCompilation/ComputeSharp.Tests.DisableDynamicCompilation.csproj
  tests/ComputeSharp.Tests.Internals/ComputeSharp.Tests.Internals.csproj
  tests/ComputeSharp.Tests.NativeLibrariesResolver/ComputeSharp.Tests.NativeLibrariesResolver.csproj
  tests/ComputeSharp.Tests.SourceGenerators/ComputeSharp.Tests.SourceGenerators.csproj
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
Labels: maintenance ⚙️

#439 Add .NET 7 and NativeAOT NuGet tests to CI
  .github/workflows/dotnet.yml
  tests/ComputeSharp.Dynamic.NuGet/ComputeSharp.Dynamic.NuGet.csproj
  tests/ComputeSharp.NuGet/ComputeSharp.NuGet.csproj
  tests/ComputeSharp.Pix.NuGet/ComputeSharp.Pix.NuGet.csproj
Labels: unit tests :test_tube:

#436 Add reflection-free NativeAOT swap chain CLI sample
  .github/workflows/dotnet.yml
  ComputeSharp.sln
  samples/ComputeSharp.ImageProcessing/ComputeSharp.ImageProcessing.csproj
  samples/ComputeSharp.Sample.FSharp/ComputeSharp.Sample.FSharp.fsproj
  samples/ComputeSharp.Sample/ComputeSharp.Sample.csproj
  samples/ComputeSharp.SwapChain.Cli/ComputeSharp.SwapChain.Cli.csproj
  samples/ComputeSharp.SwapChain.Cli/Program.cs
  samples/ComputeSharp.SwapChain.Cli/icon.ico
  samples/ComputeSharp.SwapChain/Backend/SwapChainApplication{T}.cs
Labels: samples :books:, unit tests :test_tube:

#440 Bump WinUI 3 dependencies to 1.2.221116.1
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  src/ComputeSharp.WinUI/ComputeSharp.WinUI.csproj
Labels: enhancement :sparkles:, samples :books:, maintenance ⚙️

#441 Bump all NuGet packages to latest stable
  samples/ComputeSharp.SwapChain.Uwp/ComputeSharp.SwapChain.Uwp.csproj
  src/Directory.Build.props
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
Labels: maintenance ⚙️

#432 Implement new D2D1 transform mapper infrastructure
  src/ComputeSharp.D2D1/Interfaces/ID2D1TransformMapperFactory{T}.cs
  src/ComputeSharp.D2D1/Interfaces/ID2D1TransformMapper{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1DrawInfoUpdateContext{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShaderEffect.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1PixelShaderEffectProperty.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1ResourceTextureManager.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1TransformMapperFactory{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/D2D1TransformMapper{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/D2D1TransformMapper.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/ID2D1TransformMapperInterop.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.For{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.ID2D1DrawTransformMethods.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.Properties.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/PixelShaderEffect.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/ResourceManagers/D2D1ResourceTextureManagerImpl.ID2D1ResourceTextureManager.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/ResourceManagers/D2D1ResourceTextureManagerImpl.ID2D1ResourceTextureManagerInternal.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/ResourceManagers/D2D1ResourceTextureManagerImpl.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/ResourceManagers/ID2D1ResourceTextureManager.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/ResourceManagers/ID2D1ResourceTextureManagerInternal.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/D2D1DrawInfoUpdateContextImpl.ID2D1DrawInfoUpdateContex.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/D2D1DrawInfoUpdateContextImpl.ID2D1DrawInfoUpdateContexInternal.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/D2D1DrawInfoUpdateContextImpl.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/D2D1TransformMapperImpl.ID2D1TransformMapper.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/D2D1TransformMapperImpl.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/ID2D1DrawInfoUpdateContext.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/ID2D1DrawInfoUpdateContextInternal.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Effects/TransformMappers/ID2D1TransformMapper.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Factories/Abstract/D2D1TransformMapperFactory{T, TParameters, TTransformMapper}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Factories/Abstract/D2D1TransformMapperParametersAccessor{T, TParameters}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Factories/Abstract/D2D1TransformMapper{T, TParameters}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Factories/D2D1AffineTransformMapper{T}.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Factories/D2D1InflateTransformMapperFactory.cs
  src/ComputeSharp.D2D1/Shaders/Interop/Factories/D2D1InflateTransformMapper{T}.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1DrawInfoDispatchDataLoader.cs
  src/ComputeSharp.D2D1/Shaders/Loaders/D2D1DrawInfoUpdateContextDispatchDataLoader.cs
  src/TerraFX.Interop.Windows.D2D1/TerraFX.Interop.Windows.D2D1.projitems
  src/TerraFX.Interop.Windows.D2D1/Windows/shared/winerror/RO.cs
  tests/ComputeSharp.D2D1.Tests/Assets/RadialFadeOut.png
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.D2D1.Tests/D2D1EffectRegistrationDataTests.cs
  tests/ComputeSharp.D2D1.Tests/D2D1PixelShaderEffectTests.cs
  tests/ComputeSharp.D2D1.Tests/D2D1ResourceTextureManagerTests.cs
  tests/ComputeSharp.D2D1.Tests/D2D1TransformMapperTests.cs
  tests/ComputeSharp.D2D1.Tests/Effects/BokehBlurEffect.cs
  tests/ComputeSharp.D2D1.Tests/Helpers/D2D1TestRunner.cs
Labels: enhancement :sparkles:, feature 🎉, breaking change :bomb:
