Repository Sergio0694/ComputeSharp, pull requests merged in 2022-01, with the labels that each got.

#188 Add AppCenter analytics to UWP sample app
  .gitignore
  build/CreateBlankAppCenterToken.ps1
  samples/ComputeSharp.SwapChain.Core.Shared/ComputeSharp.SwapChain.Core.Shared.projitems
  samples/ComputeSharp.SwapChain.Core.Shared/Constants/Event.cs
  samples/ComputeSharp.SwapChain.Core.Shared/Services/DebugAnalyticsService.cs
  samples/ComputeSharp.SwapChain.Core.Shared/Services/IAnalyticsService.cs
  samples/ComputeSharp.SwapChain.Core.Shared/ViewModels/MainViewModel.cs
  samples/ComputeSharp.SwapChain.Uwp/App.xaml.cs
  samples/ComputeSharp.SwapChain.Uwp/ComputeSharp.SwapChain.Uwp.csproj
  samples/ComputeSharp.SwapChain.Uwp/Extensions/AssemblyExtensions.cs
  samples/ComputeSharp.SwapChain.Uwp/Package.appxmanifest
  samples/ComputeSharp.SwapChain.Uwp/Properties/Default.rd.xml
  samples/ComputeSharp.SwapChain.Uwp/Services/AppCenterService.cs
  samples/ComputeSharp.SwapChain.Uwp/Views/MainView.xaml
  samples/ComputeSharp.SwapChain.Uwp/Views/MainView.xaml.cs
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml.cs
Labels: enhancement :sparkles:, samples :books:

#189 ShaderPanel improvements
  samples/ComputeSharp.SwapChain.Core.Shared/Shaders/Runners/ContouredLayersRunner.cs
  src/ComputeSharp.UI/Helpers/SwapChainManager.Rendering.cs
  src/ComputeSharp.UI/Helpers/SwapChainManager.cs
  src/ComputeSharp.UI/IShaderRunner.cs
  src/ComputeSharp.UI/ShaderRunner{T}.cs
Labels: enhancement :sparkles:, optimization 🚀, feature 🎉

#191 IGraphicsResource interface
  samples/ComputeSharp.SwapChain.Core.Shared/Shaders/Runners/ContouredLayersRunner.cs
  src/ComputeSharp.UI/ShaderRunner{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Buffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IGraphicsResource.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IReadOnlyTexture2D{TPixel}.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IReadOnlyTexture3D{TPixel}.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IReadWriteTexture2D{TPixel}.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IReadWriteTexture3D{TPixel}.cs
Labels: enhancement :sparkles:, feature 🎉

#192 ComputeContext.Fill APIs, new IPixel<T, TPixel> interface
  samples/ComputeSharp.ImageProcessing/Processors/HlslBokehBlurProcessor{TPixel}.cs
  samples/ComputeSharp.ImageProcessing/Processors/HlslGaussianBlurProcessor{TPixel}.cs
  src/ComputeSharp/Core/Imaging/Bgra32.cs
  src/ComputeSharp/Core/Imaging/Interfaces/IPixel{T,TPixel}.cs
  src/ComputeSharp/Core/Imaging/R16.cs
  src/ComputeSharp/Core/Imaging/R8.cs
  src/ComputeSharp/Core/Imaging/Rg16.cs
  src/ComputeSharp/Core/Imaging/Rg32.cs
  src/ComputeSharp/Core/Imaging/Rgba32.cs
  src/ComputeSharp/Core/Imaging/Rgba64.cs
  src/ComputeSharp/Core/Imaging/__Internals/IUnorm{TPixel}.cs
  src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Resources.cs
  src/ComputeSharp/Graphics/Extensions/Interop/ID3D12GraphicsCommandListExtensions.cs
  src/ComputeSharp/Graphics/Helpers/DXGIFormatHelper.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture2D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture3D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture2D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture3D{T,TPixel}.cs
  src/ComputeSharp/Shaders/ComputeContext.cs
  src/ComputeSharp/Shaders/Extensions/ComputeContextExtensions.cs
  tests/ComputeSharp.Tests/ComputeContextTests.cs
  tests/ComputeSharp.Tests/Extensions/GraphicsDeviceExtensions.cs
  tests/ComputeSharp.Tests/Texture2DTests.Pixels.cs
  tests/ComputeSharp.Tests/Texture2DTests.Pixels.g.cs
  tests/ComputeSharp.Tests/Texture2DTests.Pixels.tt
  tests/ComputeSharp.Tests/Texture3DTests.Pixels.cs
  tests/ComputeSharp.Tests/Texture3DTests.Pixels.g.cs
  tests/ComputeSharp.Tests/Texture3DTests.Pixels.tt
Labels: enhancement :sparkles:, feature 🎉

#190 Implement packaging for ComputeSharp.Dynamic
  src/ComputeSharp.Dynamic.Package/ComputeSharp.Dynamic.Package.msbuildproj
Labels: bug fix :white_check_mark:

#194 Bugfix/shader misc
  src/ComputeSharp.Dynamic/Shaders/Translation/__Internals/ShaderCompiler.cs
  src/ComputeSharp.SourceGenerators/SyntaxRewriters/ExecuteMethodRewriter.cs
  src/ComputeSharp/Core/Intrinsics/Hlsl.g.cs
  src/ComputeSharp/Core/Intrinsics/Hlsl.ttinclude
  tests/ComputeSharp.Tests/IPixelShaderTests.cs
Labels: bug fix :white_check_mark:

#195 Fix ref returns of readonly types/interfaces
  src/ComputeSharp/Graphics/Resources/ConstantBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IReadOnlyTexture2D{TPixel}.cs
  src/ComputeSharp/Graphics/Resources/Interfaces/IReadOnlyTexture3D{TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyBuffer{T}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture2D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture3D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadOnlyTexture3D{T}.cs
Labels: enhancement :sparkles:, breaking change :bomb:

#196 Add ComputeContext.Transition APIs to sample writeable textures
  src/ComputeSharp.SourceGenerators/Mappings/HlslKnownMembers.cs
  src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Resources.cs
  src/ComputeSharp/Graphics/Helpers/__Internals/GraphicsResourceHelper.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/Texture3D{T}.cs
  src/ComputeSharp/Graphics/Resources/Enums/ResourceState.cs
  src/ComputeSharp/Graphics/Resources/Helpers/ResourceStateHelper.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture2D{T,TPixel}.ReadOnly.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture2D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture3D{T,TPixel}.ReadOnly.cs
  src/ComputeSharp/Graphics/Resources/ReadWriteTexture3D{T,TPixel}.cs
  src/ComputeSharp/Graphics/Resources/Views/TextureView2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Views/TextureView3D{T}.cs
  src/ComputeSharp/Shaders/ComputeContext.cs
  src/ComputeSharp/Shaders/Extensions/ComputeContextExtensions.cs
  tests/ComputeSharp.Tests/Assets/CityAfter1024x1024SamplingAndDashing.png
  tests/ComputeSharp.Tests/Assets/CityAfter1024x1024SamplingFrom1920x1080AndDashing.png
  tests/ComputeSharp.Tests/Assets/CityWith1920x1280Resizing.png
  tests/ComputeSharp.Tests/ComputeContextTests.cs
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
  tests/ComputeSharp.Tests/Extensions/ImagingExtensions.cs
  tests/ComputeSharp.Tests/Texture2DTests.Pixels.cs
  tests/ComputeSharp.Tests/Texture3DTests.Pixels.cs
Labels: bug fix :white_check_mark:, feature 🎉

#197 Add vertical sync option
  samples/ComputeSharp.SwapChain.Core.Shared/Constants/Event.cs
  samples/ComputeSharp.SwapChain.Core.Shared/ViewModels/MainViewModel.cs
  samples/ComputeSharp.SwapChain.Uwp/App.xaml
  samples/ComputeSharp.SwapChain.Uwp/ComputeSharp.SwapChain.Uwp.csproj
  samples/ComputeSharp.SwapChain.Uwp/Views/MainView.xaml
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml
  src/ComputeSharp.UI/Controls/AnimatedComputeShaderPanel.Properties.cs
  src/ComputeSharp.UI/Controls/AnimatedComputeShaderPanel.cs
  src/ComputeSharp.UI/Controls/ComputeShaderPanel.Properties.cs
  src/ComputeSharp.UI/Controls/ComputeShaderPanel.cs
  src/ComputeSharp.UI/Helpers/DynamicResolutionManager.cs
  src/ComputeSharp.UI/Helpers/SwapChainManager.Rendering.cs
  src/ComputeSharp.UI/Helpers/SwapChainManager.cs
Labels: enhancement :sparkles:, feature 🎉

#199 Add ArgumentNullException validation for public params
  src/ComputeSharp/Graphics/Extensions/BufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Dispatching.cs
  src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Resources.cs
  src/ComputeSharp/Graphics/Extensions/ReadBackBufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadBackTexture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadBackTexture3DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadWriteTexture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/ReadWriteTexture3DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/StructuredBufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Texture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/Texture3DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/UploadBufferExtensions.cs
  src/ComputeSharp/Graphics/Extensions/UploadTexture2DExtensions.cs
  src/ComputeSharp/Graphics/Extensions/UploadTexture3DExtensions.cs
  src/ComputeSharp/Graphics/GraphicsDevice.GetDevice.cs
  src/ComputeSharp/Graphics/Helpers/__Internals/GraphicsResourceHelper.cs
  src/ComputeSharp/Shaders/Extensions/ComputeContextExtensions.cs
Labels: enhancement :sparkles:

#200 Samples/error handling improvements
  samples/ComputeSharp.SwapChain.Core.Shared/ComputeSharp.SwapChain.Core.Shared.projitems
  samples/ComputeSharp.SwapChain.Core.Shared/Constants/Error.cs
  samples/ComputeSharp.SwapChain.Core.Shared/Constants/Event.cs
  samples/ComputeSharp.SwapChain.Core.Shared/Services/DebugAnalyticsService.cs
  samples/ComputeSharp.SwapChain.Core.Shared/Services/IAnalyticsService.cs
  samples/ComputeSharp.SwapChain.Uwp/Services/AppCenterService.cs
  samples/ComputeSharp.SwapChain.Uwp/Views/MainView.xaml
  samples/ComputeSharp.SwapChain.Uwp/Views/MainView.xaml.cs
Labels: samples :books:

#201 Use ComputeContext backend for one-shot APIs
  src/ComputeSharp/ComputeSharp.csproj
  src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Dispatching.cs
  src/ComputeSharp/Shaders/ComputeContext.cs
  src/ComputeSharp/Shaders/Dispatching/ShaderBytecodeLoader.cs
  src/ComputeSharp/Shaders/Loading/PipelineDataLoader{T}.cs
  src/ComputeSharp/Shaders/Models/ICachedShader.cs
  src/ComputeSharp/Shaders/Models/PipelineData.cs
  src/ComputeSharp/Shaders/Models/ShaderKey.cs
  src/ComputeSharp/Shaders/ShaderRunner{T}.cs
Labels: bug fix :white_check_mark:, refactoring 🧹

#203 Detect refresh rate for dynamic resolution
  src/ComputeSharp.UI/ComputeSharp.UI.projitems
  src/ComputeSharp.UI/Extensions/IDXGIAdapterExtensions.cs
  src/ComputeSharp.UI/Helpers/SwapChainManager.Rendering.cs
  src/ComputeSharp.UI/Helpers/SwapChainManager.cs
  src/ComputeSharp/Graphics/GraphicsDevice.cs
  src/TerraFX.Interop.Windows/DirectX/shared/dxgi1_2/DXGIOutput1.cs
  src/TerraFX.Interop.Windows/DirectX/shared/dxgi1_2/DXGI_MODE_DESC1.cs
  src/TerraFX.Interop.Windows/DirectX/shared/dxgicommon/DXGI_RATIONAL.cs
  src/TerraFX.Interop.Windows/DirectX/shared/dxgitype/DXGI_MODE_SCALING.cs
  src/TerraFX.Interop.Windows/DirectX/shared/dxgitype/DXGI_MODE_SCANLINE_ORDER.cs
  src/TerraFX.Interop.Windows/TerraFX.Interop.Windows.projitems
Labels: enhancement :sparkles:

#202 Add diagnostics app context switch
  src/ComputeSharp/Graphics/Extensions/Interop/HResultExtensions.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.Factory.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.ID3D12InfoQueue.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.IDXGIFactory6.cs
  src/ComputeSharp/Properties/Configuration.cs
Labels: feature 🎉

#205 Add support for global namespaces
  samples/ComputeSharp.Sample.Shared/ComputeSharp.Sample.Shared.projitems
  samples/ComputeSharp.Sample.Shared/Helpers/Formatting.cs
  samples/ComputeSharp.Sample.Shared/Program.cs
  src/ComputeSharp.SourceGenerators/AutoConstructorGenerator.cs
  src/ComputeSharp.SourceGenerators/Extensions/ISymbolExtensions.cs
  src/ComputeSharp.SourceGenerators/IShaderGenerator.Helpers.cs
Labels: bug fix :white_check_mark:

#207 Avoid target-typed new for release tracking analyzer
  src/ComputeSharp.SourceGenerators/Diagnostics/DiagnosticDescriptors.cs
Labels: bug fix :white_check_mark:

#206 Add custom .targets file to issue an error on VS2019
  src/ComputeSharp/ComputeSharp.csproj
  src/ComputeSharp/ComputeSharp.targets
Labels: enhancement :sparkles:

#208 Fix refresh rate detection on devices with no GPU outputs
  src/ComputeSharp.UI/Helpers/SwapChainManager.cs
  src/ComputeSharp/Graphics/GraphicsDevice.cs
  src/ComputeSharp/Graphics/Helpers/DeviceHelper.IDXGIFactory6.cs
Labels: bug fix :white_check_mark:
