Repository Sergio0694/ComputeSharp, pull requests merged in 2024-08, with the labels that each got.

#830 Update NuGet packages to latest versions
  samples/ComputeSharp.Benchmark/ComputeSharp.Benchmark.csproj
  samples/ComputeSharp.NativeLibrary.WinRT/ComputeSharp.NativeLibrary.WinRT.csproj
  samples/ComputeSharp.SwapChain.D2D1.Cli/ComputeSharp.SwapChain.D2D1.Cli.csproj
  src/ComputeSharp.D2D1.WinUI/ComputeSharp.D2D1.WinUI.csproj
  src/ComputeSharp.WinUI/ComputeSharp.WinUI.csproj
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes.csproj
  tests/ComputeSharp.D2D1.Tests.SourceGenerators/ComputeSharp.D2D1.Tests.SourceGenerators.csproj
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.D2D1.WinUI.Tests/ComputeSharp.D2D1.WinUI.Tests.csproj
  tests/ComputeSharp.Tests.DeviceLost/ComputeSharp.Tests.DeviceLost.csproj
  tests/ComputeSharp.Tests.DisableDynamicCompilation/ComputeSharp.Tests.DisableDynamicCompilation.csproj
  tests/ComputeSharp.Tests.Internals/ComputeSharp.Tests.Internals.csproj
  tests/ComputeSharp.Tests.NativeLibrariesResolver/ComputeSharp.Tests.NativeLibrariesResolver.csproj
  tests/ComputeSharp.Tests.SourceGenerators/ComputeSharp.Tests.SourceGenerators.csproj
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
Labels: maintenance ⚙️

#831 Add missing 'TransferTextureND<T>.View' docs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture1D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture2D{T}.cs
  src/ComputeSharp/Graphics/Resources/Abstract/TransferTexture3D{T}.cs
Labels: documentation :book:

#832 Update Windows SDK projections and CsWinRT
  samples/ComputeSharp.NativeLibrary.WinRT/ComputeSharp.NativeLibrary.WinRT.csproj
  samples/ComputeSharp.SwapChain.D2D1.Cli/ComputeSharp.SwapChain.D2D1.Cli.csproj
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  src/ComputeSharp.D2D1.WinUI/ComputeSharp.D2D1.WinUI.csproj
  src/ComputeSharp.WinUI/ComputeSharp.WinUI.csproj
  tests/ComputeSharp.D2D1.WinUI.Tests/ComputeSharp.D2D1.WinUI.Tests.csproj
Labels: maintenance ⚙️

#834 Fix new .NET analyzer warnings
  src/ComputeSharp.SourceGeneration.Hlsl/SyntaxRewriters/HlslSourceRewriter.cs
  src/ComputeSharp.WinUI/Controls/AnimatedComputeShaderPanel.Properties.cs
Labels: maintenance ⚙️

#823 Use 'CanvasAnimatedControl' from Win2D in WinUI sample
  samples/ComputeSharp.SwapChain.WinUI/Controls/D2D1AnimatedPixelShaderPanel.cs
  samples/ComputeSharp.SwapChain.WinUI/Controls/Microsoft.Graphics.Canvas.UI.Xaml/CanvasAnimatedControl.cs
  samples/ComputeSharp.SwapChain.WinUI/Controls/Microsoft.Graphics.Canvas.UI.Xaml/CanvasAnimatedDrawEventArgs.cs
  samples/ComputeSharp.SwapChain.WinUI/Controls/Microsoft.Graphics.Canvas.UI.Xaml/ICanvasAnimatedControl.cs
  samples/ComputeSharp.SwapChain.WinUI/Controls/Microsoft.Graphics.Canvas.UI/CanvasTimingInformation.cs
  src/ComputeSharp.D2D1.WinUI/ComputeSharp.D2D1.WinUI.csproj
Labels: samples :books:, maintenance ⚙️

#836 Update NuGet packages to latest versions
  samples/ComputeSharp.Sample.FSharp/ComputeSharp.Sample.FSharp.fsproj
  src/ComputeSharp.WinUI/ComputeSharp.WinUI.csproj
  tests/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes/ComputeSharp.D2D1.Tests.AssemblyLevelAttributes.csproj
  tests/ComputeSharp.D2D1.Tests.SourceGenerators/ComputeSharp.D2D1.Tests.SourceGenerators.csproj
  tests/ComputeSharp.D2D1.Tests/ComputeSharp.D2D1.Tests.csproj
  tests/ComputeSharp.D2D1.WinUI.Tests/ComputeSharp.D2D1.WinUI.Tests.csproj
  tests/ComputeSharp.Tests.DeviceLost/ComputeSharp.Tests.DeviceLost.csproj
  tests/ComputeSharp.Tests.DisableDynamicCompilation/ComputeSharp.Tests.DisableDynamicCompilation.csproj
  tests/ComputeSharp.Tests.Internals/ComputeSharp.Tests.Internals.csproj
  tests/ComputeSharp.Tests.NativeLibrariesResolver/ComputeSharp.Tests.NativeLibrariesResolver.csproj
  tests/ComputeSharp.Tests.SourceGenerators/ComputeSharp.Tests.SourceGenerators.csproj
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
Labels: maintenance ⚙️

#837 Update badge image in readme
  README.md
Labels: documentation :book:

#838 Tweak .targets for published projects
  src/Directory.Build.props
  src/Directory.Build.targets
Labels: documentation :book:, maintenance ⚙️

#840 Remove analytics service from WinUI sample app
  samples/ComputeSharp.SwapChain.WinUI/Constants/Error.cs
  samples/ComputeSharp.SwapChain.WinUI/Constants/Event.cs
  samples/ComputeSharp.SwapChain.WinUI/Services/DebugAnalyticsService.cs
  samples/ComputeSharp.SwapChain.WinUI/Services/IAnalyticsService.cs
  samples/ComputeSharp.SwapChain.WinUI/ViewModels/MainViewModel.cs
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml.cs
Labels: samples :books:

#841 Remove 'CommunityToolkit.Diagnostics'
  samples/ComputeSharp.Benchmark/ComputeSharp.Benchmark.csproj
  samples/ComputeSharp.ImageProcessing/ComputeSharp.ImageProcessing.csproj
  samples/ComputeSharp.ImageProcessing/Processors/HlslBokehBlurProcessor.Implementation.cs
  samples/ComputeSharp.ImageProcessing/Processors/HlslBokehBlurProcessor.cs
  samples/ComputeSharp.ImageProcessing/Processors/HlslGaussianBlurProcessor.Implementation.cs
  samples/ComputeSharp.ImageProcessing/Processors/HlslGaussianBlurProcessor.cs
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  tests/ComputeSharp.Tests.DeviceLost/ComputeSharp.Tests.DeviceLost.csproj
  tests/ComputeSharp.Tests.DeviceLost/Extensions/DeviceExtensions.cs
  tests/ComputeSharp.Tests.DisableDynamicCompilation/ComputeSharp.Tests.DisableDynamicCompilation.csproj
  tests/ComputeSharp.Tests.Internals/ComputeSharp.Tests.Internals.csproj
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
  tests/ComputeSharp.Tests/Extensions/DeviceExtensions.cs
  tests/ComputeSharp.Tests/Extensions/ImagingExtensions.cs
Labels: maintenance ⚙️

#842 Add NativeAOT support to WinUI 3 sample app
  .github/workflows/dotnet.yml
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  samples/ComputeSharp.SwapChain.WinUI/Controls/D2D1AnimatedPixelShaderPanel.cs
  samples/ComputeSharp.SwapChain.WinUI/Properties/PublishProfiles/win-arm64.pubxml
  samples/ComputeSharp.SwapChain.WinUI/Properties/PublishProfiles/win-x64.pubxml
  samples/ComputeSharp.SwapChain.WinUI/Shaders/PixelShaderEffect.cs
  samples/ComputeSharp.SwapChain.WinUI/Shaders/Runners/D2D1ContouredLayersRunner.cs
  samples/ComputeSharp.SwapChain.WinUI/ViewModels/MainViewModel.cs
  samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml
  src/ComputeSharp.WinUI/ComputeSharp.WinUI.csproj
Labels: samples :books:

#843 Update .NET Community Toolkit packages to 8.3.0
  samples/ComputeSharp.SwapChain.WinUI/ComputeSharp.SwapChain.WinUI.csproj
  tests/ComputeSharp.Tests/ComputeSharp.Tests.csproj
Labels: maintenance ⚙️

#844 Addresses limitations of detecting ImageFormat / ContainerFormat from the file extension
  src/ComputeSharp/Graphics/Helpers/WICFormatHelper.cs
  src/ComputeSharp/Graphics/Helpers/WICHelper.cs
Labels: enhancement :sparkles:

#845 Update Win2D sample to use WinAppSDK's 'AppWindow' and new APIs
  samples/ComputeSharp.SwapChain.D2D1.Cli/Backend/ABI.Microsoft.Graphics.Canvas/ICanvasFactoryNative.cs
  samples/ComputeSharp.SwapChain.D2D1.Cli/Backend/Win32Application.cs
  samples/ComputeSharp.SwapChain.D2D1.Cli/Backend/Win32ApplicationRunner.cs
  samples/ComputeSharp.SwapChain.D2D1.Cli/ComputeSharp.SwapChain.D2D1.Cli.csproj
  samples/ComputeSharp.SwapChain.D2D1.Cli/Program.cs
Labels: samples :books:

#846 Stop emitting unnecessary 'unsafe' modifiers
  src/ComputeSharp.D2D1.SourceGenerators/D2DPixelShaderDescriptorGenerator.ConstantBuffer.cs
  tests/ComputeSharp.D2D1.Tests.SourceGenerators/Test_D2DPixelShaderDescriptorGenerator.cs
Labels: enhancement :sparkles:
